version: '3.8'

services:
  # Database
  db:
    #platform: linux/amd64
    image: mysql:8.0.32
    container_name: microservice_db
    volumes:
      - microservice_db:/var/lib/docker/volumes/
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    #networks:
    #  - mysql-phpmyadmin

  # phpmyadmin
  #phpmyadmin:
   # depends_on:
    #  - db
    #image: phpmyadmin
    #container_name: phpmyadmin
    #restart: always
    #ports:
    #  - "8090:80"
    #environment:
    #  PMA_HOST: db
    #  MYSQL_ROOT_PASSWORD: 12345
   # networks:
   #   - mysql-phpmyadmin

#networks:
 # mysql-phpmyadmin:
   # driver: bridge

volumes:
  microservice_db: