version: '3.8'

services:
  # Database
  microservice_db:
    image: mysql:8.0.32
    container_name: microservice_db
    volumes:
      - microservice_db:/var/lib/docker/volumes/
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    networks:
      - mysql-group

  fraud_db:
    image: mysql:8.0.32
    container_name: fraud_db
    volumes:
      - fraud_db:/var/lib/docker/volumes/
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fraud_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    networks:
      - mysql-group

networks:
  mysql-group:
   # driver: bridge

volumes:
  microservice_db:
  fraud_db: